spring.application.name=getway-server
server.port=9999
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


springdoc.swagger-ui.urls[0].name=Products Service
springdoc.swagger-ui.urls[0].url=/PRODUCTS-SERVICE/api-docs

springdoc.swagger-ui.urls[1].name=Commandes Service
springdoc.swagger-ui.urls[1].url=/COMMANDES-SERVICE/api-docs







spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}